spring.application.name=foodiesapi
spring.data.mongodb.uri=${MONGODB_URL}

aws.access.key=${AWS_ACCESS_KEY}
aws.secret.key=${AWS_SECRET_KEY}
aws.region=${AWS_REGION}
aws.s3.bucketname=${AWS_S3_BUCKETNAME}

jwt.secret.key=${JWT_SECRET_KEY}
